[package]
name = "orbis"
version = "0.1.0"
edition = "2021"
description = "Rigid body kinematics for orbital applications"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
